name: publish

on: [push]

jobs:
  publish-tg-subcription-image:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Login to GitHub Container Registry
      run: |
        echo $CR_PAT | docker login ghcr.io -u ${{ github.actor }} --password-stdin
      env:
        CR_PAT: ${{ secrets.CR_PAT }}

    - name: Build the tg-subscription Docker image
      run: |
        docker build . --tag ghcr.io/richardokonicha/tg-subscription:latest
        docker push ghcr.io/richardokonicha/tg-subscription:latest